scaling: "disable" # Any input except "enable" will disable it
scaler: "robust" # Mustn't be blanked if scaling is enable
imputation: "median" # Mustn't be blanked
balance_method: "SMOTE" # None to not use any method
outliers_method: "attribute_wise" # None to not use any method
